name: x86-64 Pull and Save Docker Image
on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        disk-size: 50GB  # 将磁盘空间增加到 50 GB

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Clean up Docker to free space
      run: |
        docker system prune -a -f
        docker volume prune -f
        docker image prune -a -f

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        for image in "${image_array[@]}"; do
          docker pull "${image}" --platform "linux/amd64"
          docker save "${image}" -o "${image//\//_}-amd64.tar"
          docker rmi "${image}"  # 拉取并保存后立即删除镜像
        done

    - name: Install pigz for faster compression
      run: sudo apt-get install -y pigz

    - name: Compress the TAR files
      run: tar -cf - *-amd64.tar | pigz -9 > x86-64-images.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        rm *-amd64.tar
        rm x86-64-images.tar.gz
